### ISSUE TITLE
How to train new models

### ISSUE THREAD

**Issue by vertgo** [CPJKU/madmom_models#12]
Sorry, might be a noob question. Is there any sample code to train a new model and adapt it for use in madmom? I have a corpus of a specialized instrument sounds and would like to use madmom to recognize.

**Comment by superbock** [comment]
Unfortunately no. I never managed to clean up the training code to be released publicly. However, it is quite simple to train a network. Simply use some features (e.g. those already used for existing networks) and train them with the corpus/targets at hand. Converting a network to madmom is also straight forward as it usually implies only instantiating the layers with the trained weights (you might need to transpose/shift the dimensions) and and bundle them as a neural network.

I hope to put together a tutorial or add some example code to the docs at a certain point in time. Not sure when this will happen, though.

**Comment by vertgo** [comment]
hi, thanks @superbock for getting back to me. When you say "simply use some features" do you mean a software feature like chord recognition, or an audio feature like MFCC's?


Also, i wouldn't mind looking at uncleaned up code. Lord knows that's half of my day anyway

**Comment by superbock** [comment]
I meant features like spectrograms or MFCCs. Regarding the training code I am afraid that my last comment said it all, the code is *really* not ready to be used by anyone else yet.

**Comment by BenLad17** [comment]
> I hope to put together a tutorial or add some example code to the docs at a certain point in time. Not sure when this will happen, though.

Is there a chance this will happen anytime soon? @superbock
I would highly appreciate it! 😃

**Comment by superbock** [comment]
Together with Alex Schindler and Tom Lidy I gave a tutorial at ISMIR 2018, you can access the slides/code [here](https://github.com/slychief/ismir2018_tutorial), please have a look at part 3.
